name: Luban Workshop
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: windows-latest
    name: Build & Publish
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Build
      run:  dotnet build ./src/Luban.UI/Luban.UI.Desktop/
