name: Luban Workshop
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: windows-latest
    name: Build App
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Build
      run:  dotnet publish --sc -c Release ./src/Luban.UI/Luban.UI.Browser/
    - name: Publish
      uses: actions/deploy-pages@v4
      with:
        target-branch: publish/web      # 目标分支
        publish-dir: './build/publish/Luban.UI.Browser/release'
