name: Luban Workshop
on:
  push:
    branches: ["master"]
  workflow_dispatch:
 
permissions:
  id-token: write
  contents: write
  pages: write

concurrency:
  group: "Luban"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build WASM
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Install tools
      run: dotnet workload install wasm-tools
        
    - name: Build
      run:  dotnet publish --sc -c Release ./src/Luban.UI/Luban.UI.Browser/

    - name: Publish to github
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: './build/publish/Luban.UI.Browser/release/wwwroot'
        publish_branch: publish/web
        exclude_assets: '**/*.pdb'
        
    - name: Publish to custom server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USER}}
        password: ${{secrets.FTP_PW}}
        local-dir: ./build/publish/Luban.UI.Browser/release/
        server-dir: ./luban.app/web/
        dangerous-clean-slate: true
        exclude: |
          **/*.pdb

  plugins:
    runs-on: ubuntu-latest
    name: Build plugin
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
        
    - name: Build
      run:  dotnet publish -c Release ./test/PluginTest/
      
    - name: Publish to custom server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USER}}
        password: ${{secrets.FTP_PW}}
        local-dir: ./build/publish/PluginTest/release/
        server-dir: ./luban/plugins/com.test.plugintest/
        dangerous-clean-slate: true
        exclude: |
          **/*.pdb
          **/[Ll]uban.?(*.)dll

  Server:
    runs-on: ubuntu-latest

    name: Build Server
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
        
    - name: Build
      run:  dotnet publish --sc -c Release ./src/Luban.Server/Luban.Server/
        
    - name: Publish to custom server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USER}}
        password: ${{secrets.FTP_PW}}
        local-dir: ./build/publish/Luban.UI.Browser/release/
        server-dir: ./luban.server
        dangerous-clean-slate: true
        exclude: |
          **/*.pdb
